name: mof-thermal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - ase
  - pip
  - pip:
      - tensorflow
      - pymatgen
      - molSimplify

